fishing:
  x: 1551
  y: 511
  width: 355
  height: 750
  timeouts:
    loop:
      min: 0.01
      max: 0.01
    notice:
      min: 1.5
      max: 2.0
    reeling:
      min: 1.0
      max: 1.7
    pause:
      min: 0.5
      max: 1.5
    cast:
      min: 2.0
      max: 2.0
repairing:
  x: 1622
  y: 840
  length: 25
  every: 600
  enable: 1
  timeouts:
    arm_disarm:
      min: 2
      max: 2
    inventory:
      min: 2
      max: 2
    repair:
      min: 2
      max: 2
    confirm:
      min: 2
      max: 2
bait:
  bait_x: 1655
  bait_y: 650
  equip_button_x: 1805
  equip_button_y: 1005
  length: 25
  enable: 0
  timeouts:
    select:
      min: 0.1
      max: 1
    confirm:
      min: 0.1
      max: 1
colors:
  green:
    r: 4
    g: 227
    b: 162
  brown:
    r: 230
    g: 110
    b: 22
  red:
    r: 109
    g: 18
    b: 21
resolution:
  x: 5120
  y: 2160
log_lvl: INFO
